- kite_feeds.json
Mostly in Estonian, but also Russian, English and Ukrainian.
Closes #3
> feat(kite_feed): add estonia

- kite_feeds.json
Fixes #3 by removing mixed languages and leaving only Estonian
> fix(kite_feeds): remove sources to improve quality in Estonia feed

- kite_feeds.json
Trying to improve the quality by making all sources in Estonian.
> fix(kite_feeds): make all estonian sources same language

- kite_feeds.json
news.google/ojoioeotrigo
Category: science, politics, health
Description: google news about "O Joio e o Trigo" site RSS: https://news.google.com/rss/search?q=site%3Ahttps%3A%2F%2Fojoioeotrigo.com.br&hl=pt-BR&gl=BR&ceid=BR%3Apt-419
news.google/deolhonosruralistas
Category: politics
Description: google news about "De olho nos ruralistas" site RSS: https://news.google.com/rss/search?q=site%3Ahttps%3A%2F%2Fdeolhonosruralistas.com.br&hl=pt-BR&gl=BR&ceid=BR%3Apt-419
news.google/apublica
Category: politics
Description: google news about "Agência Pública" site RSS: https://news.google.com/rss/search?q=site%3Ahttps%3A%2F%2Fapublica.org&hl=pt-BR&gl=BR&ceid=BR%3Apt-419
news.google/intercept
Category: politics
Description: google news about "Intercept Brasil" site RSS: …
> Brazil feed add 2 kite_feeds.json

- kite_feeds.json
> feat(kite_feeds): add europe news feed

- media_data.json
As discussed on discord, let's stick to indisputabile facts - also in the description.
> feat(media_data): remove description bits sourced from ssm

- media_data.json
Add any sources that were overlooked during the initial data collection.
> feat(media_data): add more source metadata for existing categories

- kite_feeds.json
Add news sources for the German state Hesse (Hessen)
> Add Germany | Hesse to kite_feeds.json

- kite_feeds.json
- media_data.json
it's a mix of french and dutch, which should be fine but yeah.
Sources for media data: (hope wikipedia is ok?) (in the order i added them)
https://en.wikipedia.org/wiki/VRT_(broadcaster)
https://en.wikipedia.org/wiki/RTBF
https://en.wikipedia.org/wiki/Sporza
https://en.wikipedia.org/wiki/Het_Laatste_Nieuws
https://en.wikipedia.org/wiki/De_Morgen
https://en.wikipedia.org/wiki/Le_Soir
https://en.wikipedia.org/wiki/De_Standaard
https://en.wikipedia.org/wiki/Het_Nieuwsblad
https://en.wikipedia.org/wiki/La_Libre_Belgique
https://en.wikipedia.org/wiki/De_Tijd
https://en.wikipedia.org/wiki/Knack_(magazine)
https://fr.wikipedia.org/wiki/Groupe_Sudmedia
https://en.wikipedia.org/wiki/Gazet_van_Antwerpen
https://en.wikipedia.org/wiki/Het_Belang_van_Limburg
https://en.wikipedia.org/wiki/Bruzz …
> Added Belgium feed

- kite.html
- Fixed a typo
- Improved the wording in various sections of the About Kite window
> Small fixes to the About Kite section

- kite_feeds.json
appended the kite_feeds.json with news feeds on Israel in English
> add news feeds on israel in english

- media_data.json
As a follow up to #60, this PR updates `media_data.json` for the recently added New Zealand news sources.
> Add media data for NZ sources

- kite_feeds.json
Added all non "world news" feeds from 2 major french daily newspapers.
> Added feeds for France

- media_data.json
As it says on the tin pretty much.
> Add further media data for NZ sources

- package-lock.json
- src/main.mjs
> fix fetch url

- kite_feeds.json
Added a new small blog by a KDE developer/youtuber (who has various other authors make articles for this site
> add thelibre.news

- kite_feeds.json
all credits to @neilio, closes #96
> feat: add apple world category

- kite_feeds.json
I added more, it was hard to find more sources. The Philippines doesn't have a lot of reputable news agencies.
> feat: more philippine news sources

- kite_feeds.json
> Include country Austria

- kite_feeds.json
JTBC is a South Korean TV broadcaster. I'd appreciate it if you could add my changes to the feed.
Source: https://news.jtbc.co.kr/rss
> Add JTBC News Feeds (South Korea)

- kite_feeds.json
Added Podcast Rex; removed an errant comma
> Added Podcast Rex

- kite_feeds.json
I'd like to add The Conversation AU to the Australian feeds.
> Add The Conversaton AU to Australian feeds

- kite_feeds.json
Hi,
These are just some extra feeds to add to the Africa topic.
> adding more africa english feeds
